//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bang_Gia_Tin
    {
        public int ID_Gia { get; set; }
        public Nullable<int> ID_LoaiTin { get; set; }
        public string Thoi_Gian { get; set; }
        public Nullable<decimal> Gia_Goc { get; set; }
        public Nullable<decimal> Gia_Giam { get; set; }
        public Nullable<int> Ty_Le_Giam { get; set; }
        public string Ghi_Chu { get; set; }
    
        public virtual Loai_Tin Loai_Tin { get; set; }
    }
}
