//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hinh_Anh
    {
        public int ID_Hinh_Anh { get; set; }
        public int ID_Phong_Tro { get; set; }
        public string Url_Anh { get; set; }
    
        public virtual Phong_Tro Phong_Tro { get; set; }
    }
}
