//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loai_Tin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loai_Tin()
        {
            this.Bang_Gia_Tin = new HashSet<Bang_Gia_Tin>();
            this.Phong_Tro = new HashSet<Phong_Tro>();
        }
    
        public int ID_LoaiTin { get; set; }
        public string Ten_LoaiTin { get; set; }
        public Nullable<int> CapDo { get; set; }
        public string Mau_TieuDe { get; set; }
        public string KichThuoc { get; set; }
        public Nullable<bool> Tu_Dong_Duyet { get; set; }
        public Nullable<bool> Hien_Thi_Goi_Dien { get; set; }
        public Nullable<bool> Trang_Thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bang_Gia_Tin> Bang_Gia_Tin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong_Tro> Phong_Tro { get; set; }
    }
}
