//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongTro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DaTa_Phong_TroEntities5 : DbContext
    {
        public DaTa_Phong_TroEntities5()
            : base("name=DaTa_Phong_TroEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bang_Gia_Tin> Bang_Gia_Tin { get; set; }
        public virtual DbSet<Chu_De> Chu_De { get; set; }
        public virtual DbSet<Hinh_Anh> Hinh_Anh { get; set; }
        public virtual DbSet<Khu_Vuc> Khu_Vuc { get; set; }
        public virtual DbSet<Loai_Tin> Loai_Tin { get; set; }
        public virtual DbSet<Noi_Bat> Noi_Bat { get; set; }
        public virtual DbSet<Phan_Quyen> Phan_Quyen { get; set; }
        public virtual DbSet<Phong_Tro> Phong_Tro { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tai_Khoan> Tai_Khoan { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<Yeu_Thich> Yeu_Thich { get; set; }
    }
}
