//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noi_Bat
    {
        public int ID_Noi_Bat { get; set; }
        public int ID_Phong_Tro { get; set; }
        public Nullable<bool> Day_du_noi_that { get; set; }
        public Nullable<bool> Co_gac { get; set; }
        public Nullable<bool> Ke_bep { get; set; }
        public Nullable<bool> Co_may_lanh { get; set; }
        public Nullable<bool> Co_may_giat { get; set; }
        public Nullable<bool> Co_tu_lanh { get; set; }
        public Nullable<bool> Co_thang_may { get; set; }
        public Nullable<bool> Khong_chung_chu { get; set; }
        public Nullable<bool> Gio_giac_tu_do { get; set; }
        public Nullable<bool> Co_bao_ve_24_24 { get; set; }
    
        public virtual Phong_Tro Phong_Tro { get; set; }
    }
}
