//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong_Tro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong_Tro()
        {
            this.Hinh_Anh = new HashSet<Hinh_Anh>();
            this.Noi_Bat = new HashSet<Noi_Bat>();
            this.Videos = new HashSet<Video>();
            this.Yeu_Thich = new HashSet<Yeu_Thich>();
        }
    
        public int ID_Phong_Tro { get; set; }
        public Nullable<int> ID_KV { get; set; }
        public Nullable<int> ID_CD { get; set; }
        public Nullable<int> ID_LoaiTin { get; set; }
        public Nullable<int> ID_TK { get; set; }
        public string Ten_Phong { get; set; }
        public Nullable<double> Dien_Tich { get; set; }
        public string Dia_Chi { get; set; }
        public string Mo_Ta { get; set; }
        public Nullable<decimal> Gia_Ca { get; set; }
        public Nullable<System.DateTime> Ngay_Dang { get; set; }
        public Nullable<System.DateTime> Ngay_Het_Han { get; set; }
        public Nullable<bool> Trang_Thai { get; set; }
        public Nullable<decimal> Gia_Duyet { get; set; }
    
        public virtual Chu_De Chu_De { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hinh_Anh> Hinh_Anh { get; set; }
        public virtual Khu_Vuc Khu_Vuc { get; set; }
        public virtual Loai_Tin Loai_Tin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Noi_Bat> Noi_Bat { get; set; }
        public virtual Tai_Khoan Tai_Khoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video> Videos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yeu_Thich> Yeu_Thich { get; set; }
    }
}
