//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tai_Khoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tai_Khoan()
        {
            this.Phong_Tro = new HashSet<Phong_Tro>();
            this.Yeu_Thich = new HashSet<Yeu_Thich>();
        }
    
        public int ID_Tk { get; set; }
        public int ID_Phan_Quyen { get; set; }
        public string User_Name { get; set; }
        public string Pass { get; set; }
        public string Name { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> Ngay_Tao { get; set; }
        public string Dia_Chi { get; set; }
        public string Avata { get; set; }
        public Nullable<bool> Trang_Thai { get; set; }
    
        public virtual Phan_Quyen Phan_Quyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong_Tro> Phong_Tro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yeu_Thich> Yeu_Thich { get; set; }
    }
}
