//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongTro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yeu_Thich
    {
        public int ID_YT { get; set; }
        public int ID_Phong_Tro { get; set; }
        public int ID_TK { get; set; }
    
        public virtual Phong_Tro Phong_Tro { get; set; }
        public virtual Tai_Khoan Tai_Khoan { get; set; }
    }
}
